let courses = [
  {
    id: 1,
    title: "Dancing",
    description: "Explore various dance styles and techniques while improving coordination, rhythm, and confidence.",
    price: 20.0,
    location: "Dance Studio",
    image: "images/dancing.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 2,
    title: "Programming",
    description: "Learn the fundamentals of coding and computer science through interactive projects and problem-solving exercises.",
    price: 20.0,
    location: "DKP",
    image: "images/programming.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 3,
    title: "Public Speaking",
    description: "Develop effective communication skills, overcome stage fright, and learn to deliver compelling speeches and presentations.",
    price: 20.0,
    location: "DKP",
    image: "images/pspeaking.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 4,
    title: "Chess",
    description: "Sharpen strategic thinking, problem-solving, and concentration skills through the game of chess.",
    price: 20.0,
    location: "DKP",
    image: "images/chess.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 5,
    title: "Drama",
    description: "Express creativity, build confidence, and develop acting skills through improvisation, role-playing, and script analysis.",
    price: 20.0,
    location: "DKP",
    image: "images/drama.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 6,
    title: "English",
    description: "Enhance language proficiency, reading comprehension, and writing skills through engaging activities and literature exploration.",
    price: 20.0,
    location: "DKP",
    image: "images/english.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 7,
    title: "Mathematics",
    description: "Strengthen mathematical concepts, problem-solving abilities, and critical thinking skills through hands-on activities and puzzles.",
    price: 20.0,
    location: "DKP",
    image: "images/maths.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 8,
    title: "Photography",
    description: " Explore the art of photography, learn camera techniques, composition, and editing skills to capture memorable moments.",
    price: 20.0,
    location: "DKP",
    image: "images/photography.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 9,
    title: "Arabic",
    description: "Immerse in the rich language and culture of Arabic through language instruction, conversation practice, and cultural activities.",
    price: 20.0,
    location: "DKP",
    image: "images/arabic.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 10,
    title: "Artwork",
    description: "Unleash creativity, experiment with various art mediums, and develop artistic skills through guided projects and techniques.",
    price: 20.0,
    location: "DKP",
    image: "images/arts.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 11,
    title: "Cooking",
    description: " Discover the joy of cooking, learn culinary techniques, recipes, and nutrition while preparing delicious dishes.",
    price: 20.0,
    location: "DKP",
    image: "images/cooking.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 12,
    title: "Swimming",
    description: "Learn essential swimming strokes, water safety skills, and build endurance in a supportive environment.",
    price: 20.0,
    location: "DKP",
    image: "images/swimming.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 13,
    title: "Robotics",
    description: "Dive into the world of robotics, learn about automation, programming, and engineering principles through hands-on projects.",
    price: 20.0,
    location: "DKP",
    image: "images/robotics.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 14,
    title: "Qur'an",
    description: " Explore the teachings and recitation of the Quran, deepen spiritual understanding, and develop memorization skills.",
    price: 20.0,
    location: "DKP",
    image: "images/quran.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 15,
    title: "Football",
    description: " Enhance teamwork, coordination, and physical fitness while learning the rules and strategies of football.",
    price: 20.0,
    location: "DKP",
    image: "images/football.jpg",
    availableInventory: 5,
    rating: 4,
  },
];
