let courses = [
  {
    id: 1,
    title: "Dancing",
    description: "Mathematics",
    price: 20.0,
    location: "DKP",
    image: "images/dancing.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 2,
    title: "Programming",
    description: "Mathematics",
    price: 20.0,
    location: "DKP",
    image: "images/programming.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 3,
    title: "Public Speaking",
    description: "Mathematics",
    price: 20.0,
    location: "DKP",
    image: "images/pspeaking.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 4,
    title: "Chess",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/chess.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 5,
    title: "Drama",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/drama.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 6,
    title: "English",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/english.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 7,
    title: "Mathematics",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/maths.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 8,
    title: "Photography",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/photography.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 9,
    title: "Arabic",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/arabic.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 10,
    title: "Artwork",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/arts.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 11,
    title: "Cooking",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/cooking.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 12,
    title: "Swimming",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/swimming.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 13,
    title: "Robotics",
    description: "",
    price: 20.0,
    location: "DKP",
    image: "images/robotics.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 14,
    title: "Qur'an",
    description: "learn Quran",
    price: 20.0,
    location: "DKP",
    image: "images/quran.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 15,
    title: "Football",
    description: "Train with....",
    price: 20.0,
    location: "DKP",
    image: "images/football.jpg",
    availableInventory: 5,
    rating: 4,
  },
];
